src/main/java/com/blinkseven/cafe/form/CoffeeListForm.java
package com.blinkseven.cafe.form;

import java.util.List;

public class CoffeeListForm {

    private List<Coffee> coffee;

    public CoffeeListForm() {}

    public List<Coffee> getCoffee() {
        return coffee;
    }

    public void setCoffee(List<Coffee> coffee) {
        this.coffee = coffee;
    }
}

src/main/java/com/blinkseven/cafe/model/CartLineInfo.java
package com.blinkseven.cafe.model;

import org.springframework.context.ApplicationContext;
import org.springframework.context.support.GenericXmlApplicationContext;

public class CartLineInfo {

    private CoffeeTypeInfo coffeeTypeInfo;
    private int quantity;
    private int n;

    private PriceCalculator priceCalculator;

    public CartLineInfo() {
        ApplicationContext ctx = new GenericXmlApplicationContext("beans.xml");
        priceCalculator = (PriceCalculator) ctx.getBean("priceCalculator");
    }

    public CoffeeTypeInfo getCoffeeTypeInfo() {
        return coffeeTypeInfo;
    }

    public void setCoffeeTypeInfo(CoffeeTypeInfo coffeeTypeInfo) {
        this.coffeeTypeInfo = coffeeTypeInfo;
    }

    public int getQuantity() {
        return quantity;
    }

    public void setQuantity(int quantity) {
        this.quantity = quantity;
    }

    public void setN(int n) {
        this.n = n;
    }

    public double getAmount() {
        return priceCalculator.getAmount(quantity, coffeeTypeInfo.getPrice(), n);
    }
}

src/main/webapp/WEB-INF/jsp/coffeelist.jsp
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<%@ include file="/WEB-INF/jsp/include.jsp" %>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
<head lang="${pageContext.request.locale}">
    <title><fmt:message key="label.title"/></title>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge, chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link href="https://fonts.googleapis.com/css?family=Open+Sans&amp;subset=cyrillic" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Lobster&amp;subset=cyrillic" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=PT+Mono&amp;subset=cyrillic" rel="stylesheet">

    <link rel="stylesheet" href="<c:url value="/resources/css/bootstrap.min.css"/>">
    <link rel="stylesheet" href="<c:url value="/resources/css/style.css"/>">

    <script type="text/javascript" src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
    <script type="text/javascript" src="<c:url value="/resources/js/bootstrap.min.js"/>"></script>
    <script type="text/javascript">
        function isNumber(event) {
            event = (event) ? event : window.event;
            var charCode = (event.which) ? event.which : event.keyCode;
            return !((charCode > 31 && charCode < 48) || charCode > 57);
        }

        function checkOrder() {
            // If there is at least one checked checkbox valid it.
            if (isChecked()) {
                var isValid = 0;

                $("input:text").filter(function () {
                    if ($(this).closest("tr").find("input:checkbox").is(":checked") && $(this).val() == 0) {
                        $(this).parent().addClass("has-error");
                        isValid++;
                    }
                });

                // If zero everything is fine, go next (submit).
                if (isValid === 0) {
                    return true;
                } else {
                    alert("<fmt:message key="not.zero.msg"/>");
                    return false;
                }
            } else {
                alert("<fmt:message key="must.choose.msg"/>");
                return false;
            }
        }

        function isChecked() {
            var checked = 0;
            $("input:checkbox").filter(function () {
                if ($(this).is(":checked")) {
                    checked++;
                }
            });
            return checked > 0;
        }

        $(document).ready(function () {
            // If a checkbox is unchecked remove 'has-error' class from an 'input:text'.
            $("input:checkbox").click(function () {
                if (!$(this).is(":checked")) {
                    $(this).closest("tr").find("td").removeClass("has-error");
                }
            });

            // If in an 'input:text' was an input remove 'has-error' class from this one.
            $("input:text").on("input", function () {
                $(this).parent().removeClass("has-error");
            });
        });
    </script>
</head>
<body>
<%@include file="locale.jsp" %>
<div class="outer">
    <div class="middle">
        <div class="inner-list">
            <form:form method="post" action="save" modelAttribute="coffeeListForm"
                       onsubmit="return checkOrder()">
                <div class="panel panel-default">
                    <table class="table table-hover" id="coffeeTypesTable">
                        <thead>
                        <tr>
                            <th><fmt:message key="coffee.name"/></th>
                            <th><fmt:message key="coffee.price"/></th>
                            <th><fmt:message key="coffee.quantity"/></th>
                        </tr>
                        </thead>
                        <tbody>
                        <c:forEach items="${listCoffeeTypes}" var="coffeeType" varStatus="status">
                            <input type="hidden" style="display:none;" name="coffee[${status.index}].id"
                                   value="<c:out value="${coffeeType.id}"/>">
                            <tr>
                                <td>
                                    <div class="checkbox">
                                        <label>
                                            <input type="checkbox" name="coffee[${status.index}].checked">
                                            <c:out value="${coffeeType.typeName}"/>
                                        </label>
                                    </div>
                                </td>
                                <td>
                                    <fmt:formatNumber type="number" maxFractionDigits="0" value="${coffeeType.price}"/>
                                    TGR
                                </td>
                                <td>
                                    <input type="text" name="coffee[${status.index}].quantity"
                                           class="form-control input-sm"
                                           placeholder="0" size="10" maxlength="5" onkeypress="return isNumber(event)"/>
                                </td>
                            </tr>
                        </c:forEach>
                        </tbody>
                    </table>
                    <div class="panel-footer">
                        <div class="row">
                            <div class="col-md-12 text-right">
                                <button class="btn btn-primary order-btn right" type="submit">
                                    <fmt:message key="button.next"/>
                                </button>
                            </div>
                        </div>
                    </div>
                </div>
            </form:form>
            <div class="bottom">
                <span style="color: red">*</span>
                <fmt:message key="stock.msg" var="val">
                    <fmt:param value="${n}"/>
                </fmt:message>
                - <c:out value="${val}"/>
            </div>
        </div>
    </div>
</div>

<c:if test="${emptyorder}">
    <script>
        alert("<fmt:message key="must.choose.msg"/>");
    </script>
</c:if>

<c:if test="${invalidquantity}">
    <script>
        alert("<fmt:message key="invalid.quantity.msg"/>");
    </script>
</c:if>
</body>
</html>

src/main/webapp/WEB-INF/jsp/include.jsp
<%@ page session="false"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt" %>
<%@ taglib prefix="spring" uri="http://www.springframework.org/tags"%>
<%@ taglib prefix="form" uri="http://www.springframework.org/tags/form" %>

src/main/webapp/WEB-INF/jsp/locale.jsp
<%--Change language on a page.--%>
<div class="right locale">
    <input type="button" class="btn btn-info btn-sm" onclick="location.href='?locale=en'" value="EN">
    <input type="button" class="btn btn-info btn-sm" onclick="location.href='?locale=ru'" value="RU">
</div>

src/main/webapp/WEB-INF/jsp/orderlist.jsp
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<%@ include file="/WEB-INF/jsp/include.jsp" %>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
<head lang="${pageContext.request.locale}">
    <title><fmt:message key="label.title"/></title>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge, chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link href="https://fonts.googleapis.com/css?family=Open+Sans&amp;subset=cyrillic" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Lobster&amp;subset=cyrillic" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=PT+Mono&amp;subset=cyrillic" rel="stylesheet">

    <link rel="stylesheet" href="<c:url value="/resources/css/bootstrap.min.css"/>">
    <link rel="stylesheet" href="<c:url value="/resources/css/style.css"/>">

    <script type="text/javascript" src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
    <script type="text/javascript" src="<c:url value="/resources/js/bootstrap.min.js"/>"></script>
    <script type="text/javascript">
        // Prevent to enter numbers into Name form.
        function isWord(event) {
            event = (event) ? event : window.event;
            var charCode = (event.which) ? event.which : event.keyCode;
            return (charCode > 31 && charCode < 48) || charCode > 57;
        }

        var isValidAddress = true;

        // Check if the address form is not empty.
        function confirmOrder() {
            var inputAddress = $("#inputAddress").filter(function () {
                return this.value === "";
            });
            if (inputAddress.length) {
                $("#inputAddressForm").addClass("has-error");
                $("#helpBlock").show();
                isValidAddress = false;
            }

            return isValidAddress;
        }

        $(document).ready(function () {
            // Remove 'has-error' state from an input form if an user enter something.
            $("#inputAddress").on("input", function () {
                $("#inputAddressForm").removeClass("has-error");
                $(".help-block").hide();
                isValidAddress = true;
            });
        });

        function showConfirmModal() {
            $('#confirmModal').modal({backdrop: 'static', keyboard: false, show: true});
        }
    </script>
</head>
<body>
<%@include file="locale.jsp" %>
<div class="outer">
    <div class="middle">
        <div class="inner-order">
            <div class="panel panel-default panel-order">
                <table class="table">
                    <thead>
                    <tr>
                        <th><fmt:message key="coffee.name"/></th>
                        <th><fmt:message key="coffee.price"/></th>
                        <th><fmt:message key="coffee.quantity"/></th>
                        <th><fmt:message key="order.total"/></th>
                    </tr>
                    </thead>
                    <tbody>
                    <c:forEach items="${orderForm.cartLines}" var="line">
                        <tr>
                            <td><c:out value="${line.coffeeTypeInfo.name}"/></td>
                            <td><fmt:formatNumber type="number" maxFractionDigits="0"
                                                  value="${line.coffeeTypeInfo.price}"/> TGR
                            </td>
                            <td><c:out value="${line.quantity}"/></td>
                            <td>
                                <span style="color: red"><fmt:formatNumber type="number" maxFractionDigits="0"
                                                                           value="${line.amount}"/></span>
                                TGR
                            </td>
                        </tr>
                    </c:forEach>
                    <tr>
                        <td>&nbsp;</td>
                        <td>&nbsp;</td>
                        <td><b><fmt:message key="order.sum"/>:</b></td>
                        <td><fmt:formatNumber type="number" maxFractionDigits="0" value="${orderForm.sum}"/> TGR</td>
                    </tr>
                    <tr>
                        <td>&nbsp;</td>
                        <td>&nbsp;</td>
                        <td><b><fmt:message key="order.delivery"/>:</b></td>
                        <td><fmt:formatNumber type="number" maxFractionDigits="0" value="${orderForm.delivery}"/> TGR
                        </td>
                    </tr>
                    <tr>
                        <td>&nbsp;</td>
                        <td>&nbsp;</td>
                        <td><b><fmt:message key="order.total"/>:</b></td>
                        <td><fmt:formatNumber type="number" maxFractionDigits="0" value="${orderForm.total}"/> TGR</td>
                    </tr>
                    </tbody>
                </table>
            </div>
            <form:form method="post" action="order" modelAttribute="customerInfo" cssClass="form-horizontal"
                       onsubmit="return confirmOrder()">
                <div class="panel panel-default panel-order">
                    <table class="table">
                        <thead>
                        <tr>
                            <th><fmt:message key="order.delivery"/></th>
                        </tr>
                        </thead>
                        <tbody>
                        <tr>
                            <td>
                                <form class="form-horizontal">
                                    <div class="form-group" id="inputNameForm">
                                        <label for="inputName" class="col-sm-2 control-label">
                                            <fmt:message key="full.name"/>
                                        </label>
                                        <div class="col-sm-10">
                                            <fmt:message key="name.placeholder" var="namePlaceholder"/>
                                            <form:input path="name" type="text" id="inputName"
                                                        name="${customerInfo.name}" class="form-control"
                                                        placeholder="${namePlaceholder}"
                                                        onkeypress="return isWord(event)"/>
                                        </div>
                                    </div>
                                    <spring:bind path="address">
                                        <div class="form-group ${status.error ? 'has-error' : ''}"
                                             id="inputAddressForm">
                                            <label for="inputAddress" class="col-sm-2 control-label">
                                                <fmt:message key="address"/>
                                            </label>
                                            <div class="col-sm-10">
                                                <fmt:message key="address.placeholder" var="addressPlaceholder"/>
                                                <form:input path="address" type="text" id="inputAddress"
                                                            name="${customerInfo.address}"
                                                            class="form-control"
                                                            placeholder="${addressPlaceholder}"/>
                                                <form:errors path="address" cssClass="help-block"/>
                                                <span id="helpBlock" style="display: none;"
                                                      class="help-block"><fmt:message key="field.required"/></span>
                                            </div>
                                        </div>
                                    </spring:bind>
                                </form>
                            </td>
                        </tr>
                        </tbody>
                    </table>
                    <div class="panel-footer">
                        <div class="row">
                            <div class="col-md-6">
                                <a class="btn btn-default" role="button" href="${pageContext.request.contextPath}/home">
                                    <fmt:message key="button.back"/>
                                </a>
                            </div>
                            <div class="col-md-6 text-right">
                                <button type="submit" class="btn btn-primary" id="confirmButton">
                                    <fmt:message key="button.order"/>
                                </button>
                            </div>
                        </div>
                    </div>
                </div>
            </form:form>
        </div>
    </div>
</div>

<%--Successful completion of an order.--%>
<c:if test="${success}">
    <script>
        window.onload = function () {
            showConfirmModal();
        }
    </script>
</c:if>

<!-- Confirmation Modal -->
<div class="modal fade" id="confirmModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog modal-sm" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title" id="myModalLabel"><fmt:message key="confirm.msg"/></h4>
            </div>
            <div class="modal-body"><fmt:message key="order.accepted"/></div>
            <div class="modal-footer">
                <!-- <button type="button" class="btn btn-default" data-dismiss="modal">Закрыть</button> -->
                <a class="btn btn-primary" role="button" href="${pageContext.request.contextPath}/home">
                    <fmt:message key="btn.main"/>
                </a>
            </div>
        </div>
    </div>
</div>
</body>
</html>